const response = {
  semesterList: [
    {
      term: 'FALL',
      year: 2017,
      courses: [
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [0, 1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f90c32d53e64d14fdd6',
          code: '10',
          area: 'B2',
          title:
            'The Living World 3 . 0 3 . 0 3 . 0 A - 11 . 1 https : / / cmsweb . cms . sjsu . edu / psp / CSJPRD _ 1 / EMPLOYEE / SA / c / SA _ LEARNER _ SERVICES . SSS _ MY _ ACAD . GBL ? Page = SSS _ MY _ ACAD & Action = U',
          department: 'BIOL',
          __v: 2,
          credit: '&',
          description:
            'Provides students with an understanding of the most fundamental concepts of modern biology including ecology (the interaction between organisms and their environment), human inheritance, the structure and function of living organisms, evolution, strategies for survival and reproduction, and biotechnology. GE Area: B2 Notes: Not an elective in the department majors.',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe88',
          code: '102',
          title: 'Assembly Language Pr',
          department: 'CMPE',
          __v: 1,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [2],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fead',
          code: '174',
          title: 'Server Web Prog',
          department: 'CS',
          __v: 0,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe86',
          code: '42',
          title: 'Discrete Math',
          department: 'MATH',
          __v: 1,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5fdd396e2ae65e4d0859',
          code: '42W',
          title: 'Discrete Math Wksp',
          credit: '1.0',
          department: 'MATH',
          __v: 0,
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [0],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f90c32d53e64d14fdbf',
          code: '57',
          area: 'A3',
          title: 'Logic & Crit Reas',
          department: 'PHIL',
          __v: 0,
          credit: '3.0',
        },
      ],
      status: 0,
    },
    {
      term: 'SPRING',
      year: 2018,
      courses: [
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe99',
          code: '120',
          title: 'Computer Org & Arch',
          department: 'CMPE',
          __v: 1,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe95',
          code: '131',
          title: 'Software Engr I',
          department: 'CMPE',
          __v: 1,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [0, 1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe74',
          code: '10',
          area: 'E1',
          title: 'Intro to Engr',
          department: 'ENGR',
          __v: 2,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5fa7396e2ae65e4d0853',
          code: '100W',
          title: 'Engr Reports',
          department: 'ENGR',
          __v: 1,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5fdd396e2ae65e4d085a',
          code: '15A',
          title: 'Essen. US History',
          credit: '3.0',
          department: 'HIST',
          __v: 0,
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5fdd396e2ae65e4d085b',
          code: '35A',
          title: 'Begin Wt Training',
          credit: '1.0',
          department: 'KIN',
          __v: 0,
        },
      ],
      status: 0,
    },
    {
      term: 'FALL',
      year: 2018,
      courses: [
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe9d',
          code: '133',
          title: 'Software Engr II',
          department: 'CMPE',
          __v: 1,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe96',
          code: '187',
          title: 'Soft Quality Engr',
          department: 'CMPE',
          __v: 1,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe97',
          code: '146',
          title: 'Data Struct & Alg',
          department: 'CS',
          __v: 1,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5fdd396e2ae65e4d085c',
          code: '14A',
          title: 'Begin Volleyball',
          credit: '1.0',
          department: 'KIN',
          __v: 0,
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe8b',
          code: '161A',
          title: 'Appl Prob & Stats I',
          department: 'MATH',
          __v: 1,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [0],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe65',
          code: '15',
          area: 'D3',
          title: 'US & CA Government',
          department: 'POLS',
          __v: 0,
          credit: '3.0',
        },
      ],
      status: 0,
    },
    {
      term: 'SPRING',
      year: 2019,
      courses: [
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe9f',
          code: '149',
          title: 'Operating Systems',
          department: 'CS',
          __v: 1,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe91',
          code: '151',
          title: 'Object Orntd Dsgn',
          department: 'CS',
          __v: 1,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe9c',
          code: '166',
          title: 'Information Security',
          department: 'CS',
          __v: 1,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5fdd396e2ae65e4d085d',
          code: '14B',
          title: 'Inter Volleyball',
          credit: '1.0',
          department: 'KIN',
          __v: 0,
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [0],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe10',
          code: '10',
          area: 'C1',
          title: 'Art of Film',
          department: 'RTVF',
          __v: 0,
          credit: '3.0',
        },
      ],
      status: 0,
    },
    {
      term: 'FALL',
      year: 2019,
      courses: [
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe8f',
          code: '148',
          title: 'Comptr Networks I',
          department: 'CMPE',
          __v: 1,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5fdd396e2ae65e4d085e',
          code: '195E',
          title: 'Sr Design Project',
          credit: '1.0',
          department: 'CMPE',
          __v: 0,
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5f91c32d53e64d14fe94',
          code: '157A',
          title: 'Int to Dtb Mgt Sys',
          department: 'CS',
          __v: 1,
          credit: '3.0',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5fdd396e2ae65e4d085f',
          code: '111',
          title: 'Alternative Cinema',
          credit: '3.0',
          department: 'RTVF',
          __v: 0,
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9d5fdd396e2ae65e4d0860',
          code: '154',
          title: 'Formal Lang & Comput',
          credit: '3.0',
          department: 'CS',
          __v: 0,
        },
      ],
      status: 0,
    },
    {
      term: 'SPRING',
      year: 2020,
      courses: [],
      status: 1,
    },
  ],
  otherInfo: [
    '[WST]: Qualify for taking upper courses such as 100W Course',
    'AP English Literature & Compostn',
    'AP Environmental Science',
    'AP U . S . Government & Politics',
  ],
  major: 'BS Computer Engineering',
};

export default response;
